name: meetup_flutter
description: Meetup Flutter project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^6.0.5
  bloc: ^8.1.0 # business logic encapsulator and abstraction
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0 # HTTP client
  flutter_bloc: ^8.1.1 # ability to use bloc objects inside UI as widgetS
  formz: ^0.4.0-nullsafety.0 # library to use form validation via classes
  freezed: ^2.3.2 # class generators
  freezed_annotation: ^2.2.0 # class generator annotation
  get_it: ^7.1.3 # service locator
  hive: ^2.0.5 # Caching for Flutter
  hive_flutter: ^1.1.0 # helps use caching in Flutter UI
  injectable: ^2.1.0
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.3+1 # widgets that helps search for phone number and verify it locally
  keyboard_actions: ^4.1.0
  logger: ^1.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^6.0.3 # generates route classes automatically
  build_runner: ^2.1.5 # generates code
  hive_generator: ^2.0.0 # generator for extended Hive objects
  injectable_generator: ^2.1.3

flutter:
 uses-material-design: true
 generate: true

