name: meetup_flutter
description: Meetup Flutter project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0 # business logic encapsulator and abstraction
  flutter_bloc: ^8.1.1 # ability to use bloc objects inside UI as widgetS
  formz: ^0.4.0-nullsafety.0 # library to use form validation via classes
  freezed: ^2.3.2 # class generators
  freezed_annotation: ^2.2.0 # class generator annotation
  get_it: ^7.1.3 # service locator
  injectable: ^2.1.0
  dartz: ^0.10.0-nullsafety.2
  intl_phone_number_input: ^0.7.0+1 # widgets that helps search for phone number and verify it locally
  keyboard_actions: ^4.1.0
  logger: ^1.0.0
  dio: ^4.0.0 # HTTP client
  intl: ^0.17.0
  go_router: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.5 # generates code
  injectable_generator: ^2.1.3

flutter:
 uses-material-design: true
 generate: true

